# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1aca8fdef468bf8ddfcb09d7e4840ea85a9b6a62b1932c70dc2c875cfbfaee03535005bb67ca6473b9312020f1bf4177efed5c4f9fe9187886e6f145d0a7a0c8

test:
  secret_key_base: 07d895d0c62578f9c3dab2de636494f176a9b2249a85cc0bd0080ce4f58f0dc2929feb3301793f8bf01c86da85038b7277a5c9c0ad968d14bfaea124ab038bfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
